//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terepnaplo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terepnaplo.Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Állapot.
        /// </summary>
        internal static string Allapot {
            get {
                return ResourceManager.GetString("Allapot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunikációs hiba a szerverrel. Kérlek, próbáld újra..
        /// </summary>
        internal static string ApiError {
            get {
                return ResourceManager.GetString("ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzó jogosultság.
        /// </summary>
        internal static string ApiErrorAuth {
            get {
                return ResourceManager.GetString("ApiErrorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás üzenet.
        /// </summary>
        internal static string ApiErrorBadReq {
            get {
                return ResourceManager.GetString("ApiErrorBadReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időtúllépés.
        /// </summary>
        internal static string ApiErrorTimeout {
            get {
                return ResourceManager.GetString("ApiErrorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terepnapló.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App verzió: {0}.
        /// </summary>
        internal static string AppVersionX {
            get {
                return ResourceManager.GetString("AppVersionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonosító.
        /// </summary>
        internal static string Azonosito {
            get {
                return ResourceManager.GetString("Azonosito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejárati nyílás (mm).
        /// </summary>
        internal static string BejaratiNyilasMm {
            get {
                return ResourceManager.GetString("BejaratiNyilasMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejárat: {0} mm.
        /// </summary>
        internal static string BejaratiNyilasX {
            get {
                return ResourceManager.GetString("BejaratiNyilasX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégsem.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törölni szeretnéd ezt a biotikát?.
        /// </summary>
        internal static string ConfirmDeleteLatogatas {
            get {
                return ResourceManager.GetString("ConfirmDeleteLatogatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törölni szeretnéd ezt az odút?.
        /// </summary>
        internal static string ConfirmDeleteOdu {
            get {
                return ResourceManager.GetString("ConfirmDeleteOdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csere.
        /// </summary>
        internal static string Csere {
            get {
                return ResourceManager.GetString("Csere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum.
        /// </summary>
        internal static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés sikertelen..
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biotika törlése.
        /// </summary>
        internal static string DeleteLatogatas {
            get {
                return ResourceManager.GetString("DeleteLatogatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odú törlése.
        /// </summary>
        internal static string DeleteOdu {
            get {
                return ResourceManager.GetString("DeleteOdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosítás.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biotika módosítása.
        /// </summary>
        internal static string EditLatogatas {
            get {
                return ResourceManager.GetString("EditLatogatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odú módosítása.
        /// </summary>
        internal static string EditOdu {
            get {
                return ResourceManager.GetString("EditOdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellenőrzés.
        /// </summary>
        internal static string Ellenorzes {
            get {
                return ResourceManager.GetString("Ellenorzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Élőhelykód.
        /// </summary>
        internal static string Elohelykod {
            get {
                return ResourceManager.GetString("Elohelykod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Élőhelykód: {0}.
        /// </summary>
        internal static string ElohelykodX {
            get {
                return ResourceManager.GetString("ElohelykodX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail cím.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nem lehet üres!.
        /// </summary>
        internal static string ErrorEmpty {
            get {
                return ResourceManager.GetString("ErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faj.
        /// </summary>
        internal static string Faj {
            get {
                return ResourceManager.GetString("Faj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faj: {0}.
        /// </summary>
        internal static string FajX {
            get {
                return ResourceManager.GetString("FajX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felelős személy cím.
        /// </summary>
        internal static string FelelosSzemelyCim {
            get {
                return ResourceManager.GetString("FelelosSzemelyCim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felelős személy email.
        /// </summary>
        internal static string FelelosSzemelyEmail {
            get {
                return ResourceManager.GetString("FelelosSzemelyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felelős személy név.
        /// </summary>
        internal static string FelelosSzemelyNev {
            get {
                return ResourceManager.GetString("FelelosSzemelyNev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felelős személy telefonszám.
        /// </summary>
        internal static string FelelosSzemelyTelefonszam {
            get {
                return ResourceManager.GetString("FelelosSzemelyTelefonszam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhelyezés módja.
        /// </summary>
        internal static string FelhelyezesModja {
            get {
                return ResourceManager.GetString("FelhelyezesModja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhelyezés módja: {0}.
        /// </summary>
        internal static string FelhelyezesModjaX {
            get {
                return ResourceManager.GetString("FelhelyezesModjaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fészekanyag van.
        /// </summary>
        internal static string FeszekanyagVan {
            get {
                return ResourceManager.GetString("FeszekanyagVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiókák kora.
        /// </summary>
        internal static string FiokakKora {
            get {
                return ResourceManager.GetString("FiokakKora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiókák kora: {0}.
        /// </summary>
        internal static string FiokakKoraX {
            get {
                return ResourceManager.GetString("FiokakKoraX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiókák száma.
        /// </summary>
        internal static string FiokakSzama {
            get {
                return ResourceManager.GetString("FiokakSzama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiókák száma: {0}.
        /// </summary>
        internal static string FiokakSzamaX {
            get {
                return ResourceManager.GetString("FiokakSzamaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiókák vannak.
        /// </summary>
        internal static string FiokakVannak {
            get {
                return ResourceManager.GetString("FiokakVannak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresztnév.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS szélesség.
        /// </summary>
        internal static string GpsLatitude {
            get {
                return ResourceManager.GetString("GpsLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS szél: {0}.
        /// </summary>
        internal static string GpsLatitudeX {
            get {
                return ResourceManager.GetString("GpsLatitudeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS hosszúság.
        /// </summary>
        internal static string GpsLongitude {
            get {
                return ResourceManager.GetString("GpsLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS hossz: {0}.
        /// </summary>
        internal static string GpsLongitudeX {
            get {
                return ResourceManager.GetString("GpsLongitudeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyűrűzés.
        /// </summary>
        internal static string Gyuruzes {
            get {
                return ResourceManager.GetString("Gyuruzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdőlap.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen e-mail cím.
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugrás az odúra.
        /// </summary>
        internal static string JumpToOdu {
            get {
                return ResourceManager.GetString("JumpToOdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezelő szervezet név.
        /// </summary>
        internal static string KezeloSzervezetNev {
            get {
                return ResourceManager.GetString("KezeloSzervezetNev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kihelyezés.
        /// </summary>
        internal static string Kihelyezes {
            get {
                return ResourceManager.GetString("Kihelyezes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vezetéknév.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biotika.
        /// </summary>
        internal static string Latogatas {
            get {
                return ResourceManager.GetString("Latogatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biotika.
        /// </summary>
        internal static string Latogatasok {
            get {
                return ResourceManager.GetString("Latogatasok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betöltés....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS lokáció.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lokáció pontossága {0} méter. Újra próbálod?.
        /// </summary>
        internal static string LocationAccuracyError {
            get {
                return ResourceManager.GetString("LocationAccuracyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokáció betöltése sikertelen..
        /// </summary>
        internal static string LocationError {
            get {
                return ResourceManager.GetString("LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokáció betöltése sikertelen. Újra próbálod?.
        /// </summary>
        internal static string LocationErrorRetry {
            get {
                return ResourceManager.GetString("LocationErrorRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokáció betöltése....
        /// </summary>
        internal static string LocationLoading {
            get {
                return ResourceManager.GetString("LocationLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezve: {0}.
        /// </summary>
        internal static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikertelen bejelentkezés.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login név.
        /// </summary>
        internal static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos kijelentkezel?.
        /// </summary>
        internal static string LogoutConfirm {
            get {
                return ResourceManager.GetString("LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magasság (m).
        /// </summary>
        internal static string MagassagMeter {
            get {
                return ResourceManager.GetString("MagassagMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magasság: {0} m.
        /// </summary>
        internal static string MagassagMeterX {
            get {
                return ResourceManager.GetString("MagassagMeterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megjegyzés.
        /// </summary>
        internal static string Megjegyzes {
            get {
                return ResourceManager.GetString("Megjegyzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megjegyzések.
        /// </summary>
        internal static string Megjegyzesek {
            get {
                return ResourceManager.GetString("Megjegyzesek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzenet.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mire van helyezve.
        /// </summary>
        internal static string MireVanHelyezve {
            get {
                return ResourceManager.GetString("MireVanHelyezve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erre van helyezve: {0}.
        /// </summary>
        internal static string MireVanHelyezveX {
            get {
                return ResourceManager.GetString("MireVanHelyezveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem madár lakja.
        /// </summary>
        internal static string NemMadarLakja {
            get {
                return ResourceManager.GetString("NemMadarLakja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összes mutatása.
        /// </summary>
        internal static string NoneSelected {
            get {
                return ResourceManager.GetString("NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odú.
        /// </summary>
        internal static string Odu {
            get {
                return ResourceManager.GetString("Odu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odúazonosító.
        /// </summary>
        internal static string OduAzonosito {
            get {
                return ResourceManager.GetString("OduAzonosito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odúk.
        /// </summary>
        internal static string Oduk {
            get {
                return ResourceManager.GetString("Oduk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odútérkép.
        /// </summary>
        internal static string OduMap {
            get {
                return ResourceManager.GetString("OduMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odú tájolása.
        /// </summary>
        internal static string OduTajolasa {
            get {
                return ResourceManager.GetString("OduTajolasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tájolás: {0}.
        /// </summary>
        internal static string OduTajolasaX {
            get {
                return ResourceManager.GetString("OduTajolasaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odútelep.
        /// </summary>
        internal static string Odutelep {
            get {
                return ResourceManager.GetString("Odutelep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odútelepek.
        /// </summary>
        internal static string Odutelepek {
            get {
                return ResourceManager.GetString("Odutelepek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odútípus.
        /// </summary>
        internal static string OduTipus {
            get {
                return ResourceManager.GetString("OduTipus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odút tartó növényfaj.
        /// </summary>
        internal static string OdutTartoNovenyfaj {
            get {
                return ResourceManager.GetString("OdutTartoNovenyfaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odút tartja: {0}.
        /// </summary>
        internal static string OdutTartoNovenyfajX {
            get {
                return ResourceManager.GetString("OdutTartoNovenyfajX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó újra.
        /// </summary>
        internal static string PasswordAgain {
            get {
                return ResourceManager.GetString("PasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A két jelszó nem egyezik.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszó legalább 6 karakter hosszú legyen, tartalmazzon kis- és nagybetűt és számot, ne tartalmnazzon speciális karaktert..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Műhold.
        /// </summary>
        internal static string Satellite {
            get {
                return ResourceManager.GetString("Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sikeresen mentve..
        /// </summary>
        internal static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs kiválasztva.
        /// </summary>
        internal static string ShowEmptyMap {
            get {
                return ResourceManager.GetString("ShowEmptyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takarítás.
        /// </summary>
        internal static string Takaritas {
            get {
                return ResourceManager.GetString("Takaritas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Település.
        /// </summary>
        internal static string Telepules {
            get {
                return ResourceManager.GetString("Telepules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terepnapló.
        /// </summary>
        internal static string Terepnaplo {
            get {
                return ResourceManager.GetString("Terepnaplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Területnév.
        /// </summary>
        internal static string TeruletNev {
            get {
                return ResourceManager.GetString("TeruletNev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tevékenység.
        /// </summary>
        internal static string Tevekenyseg {
            get {
                return ResourceManager.GetString("Tevekenyseg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tojások száma.
        /// </summary>
        internal static string TojasokSzama {
            get {
                return ResourceManager.GetString("TojasokSzama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tojás.
        /// </summary>
        internal static string TojasokSzamaX {
            get {
                return ResourceManager.GetString("TojasokSzamaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tojások vannak.
        /// </summary>
        internal static string TojasokVannak {
            get {
                return ResourceManager.GetString("TojasokVannak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új Biotika.
        /// </summary>
        internal static string UjLatogatas {
            get {
                return ResourceManager.GetString("UjLatogatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új odú.
        /// </summary>
        internal static string UjOdu {
            get {
                return ResourceManager.GetString("UjOdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új odútelep.
        /// </summary>
        internal static string UjOdutelep {
            get {
                return ResourceManager.GetString("UjOdutelep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosítás sikertelen..
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üres odú.
        /// </summary>
        internal static string UresOdu {
            get {
                return ResourceManager.GetString("UresOdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM: {0}.
        /// </summary>
        internal static string Utm {
            get {
                return ResourceManager.GetString("Utm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM négyzetkód.
        /// </summary>
        internal static string UtmNegyzetKod {
            get {
                return ResourceManager.GetString("UtmNegyzetKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás felhasználónév vagy jelszó.
        /// </summary>
        internal static string WrongLoginOrPassword {
            get {
                return ResourceManager.GetString("WrongLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igen.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
