//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadarfigyeloApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MadarfigyeloApp.Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madárfigyelő.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdőlap.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Látogatások.
        /// </summary>
        internal static string Latogatasok {
            get {
                return ResourceManager.GetString("Latogatasok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betöltés....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odúk.
        /// </summary>
        internal static string Oduk {
            get {
                return ResourceManager.GetString("Oduk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odútelepek.
        /// </summary>
        internal static string Odutelepek {
            get {
                return ResourceManager.GetString("Odutelepek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új Látogatás.
        /// </summary>
        internal static string UjLatogatas {
            get {
                return ResourceManager.GetString("UjLatogatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új odú.
        /// </summary>
        internal static string UjOdu {
            get {
                return ResourceManager.GetString("UjOdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új odútelep.
        /// </summary>
        internal static string UjOdutelep {
            get {
                return ResourceManager.GetString("UjOdutelep", resourceCulture);
            }
        }
    }
}
